name: workflow-crafty-sync

env:
  UPSTREAM_URL: "https://gitlab.com/crafty-controller/crafty-web.git"
  DOWNSTREAM_BRANCH: "master"

on:
  schedule:
    # run at midnight every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - required for 'keepalive-workflow'
        uses: actions/checkout@v2
      - name: Sync GitHub/GitLab upstream Repository changes with this repo
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ secrets.TDB_PAT }}
          push_args: origin/master --force
      - name: Prevent GitHub from disabling sync after 60 days
        uses: gautamkrishnar/keepalive-workflow@master